networks:
  pokedex:
    name: pokedex-network

services:
  jaeger:
    image: jaegertracing/all-in-one:1.23
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - pokedex

  pokedex:
    build: .
    environment:
      - Jaeger:AgentHost=jaeger
    ports:
      - 5000:80
    depends_on:
      - jaeger
    networks:
      - pokedex
  