networks:
  pokedex-loadtest:
    name: pokedex-loadtest-network
        
services:
  jaeger:
    image: jaegertracing/all-in-one:1.23
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - pokedex-loadtest

  wiremock:
    image: rodolpheche/wiremock:2.28.1

    container_name: wiremock
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    ports:
      - 8080:8080
    networks:
      - pokedex-loadtest

  pokedex:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=LoadTest
    ports:
      - 5000:80
    depends_on:
      - jaeger
      - wiremock
    networks:
      - pokedex-loadtest