name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run docker environment
      run: docker-compose -f ./docker-compose-developer.yml up -d
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "Category!=LoadTest"
    - name: Close docker environment
      run: docker-compose -f ./docker-compose-developer.yml down
    - name: Build load test environment
      run: docker-compose -f ./docker-compose-loadtest.yml up -d
    - name: Execute load tests
      run: dotnet test -c Release --verbosity normal --filter "Category=LoadTest"
    - name: Close load test environment
      run: docker-compose -f ./docker-compose-loadtest.yml down
    - name: Build real environment
      run: docker-compose -f ./docker-compose.yml up -d
    - name: Close real environment
      run: docker-compose -f ./docker-compose.yml down
